services:
  benchmark:
    image: benchmarktools:latest
    container_name: bonnie_benchmarkingtools
    volumes:
      - bonnie:/bonnie/bonniebenchmark
    command: ./bonnie/run_bonnie_sudoless.sh 50

volumes:
  bonnie:

